version: 2.1

orbs:
  node: circleci/node@4.7.0
  cypress: cypress-io/cypress@2

jobs:
  build_and_test: # this can be any name you choose
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Dependencies
          command: npm i --legacy-peer-deps
      - run:
          command: npm start
          name: Start Front End Server
      - run:
          command: serve -s build
          name: Sever the build to a static server
      - run:
          name: Install Backend Server
          command: git clone https://github.com/guaj/SemesterPlanner-Server.git
      - run:
          name: Start Backend Server
          command: node SemesterPlanner-Server/src/server.js


workflows:
  test_my_app:
    jobs:
      - build_and_test
      - cypress/run:
          wait-on: 'http://localhost:3000'