version: 2.1

orbs:
  node: circleci/node@4.7.0
  cypress: cypress-io/cypress@2

jobs:
  build: # this can be any name you choose
    docker:
      - image: cimg/node:17.2.0
        environment:
          CYPRESS_email1: email1@gmail.com
          CYPRESS_email2: email2@gmail.com
          CYPRESS_email3: email3@gmail.com
          CYPRESS_password1: test
          CYPRESS_password2: test2
          CYPRESS_password3: test3
          CYPRESS_baseUrl: http://locahost:3000/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install print-env
          name: Installing print-env package from NPM
      - run:
          command: npm run build
          name: Build Front-End Application



workflows:
  test_my_app:
    jobs:
      - build
      - cypress/install:
          pre-steps:
            - checkout
            - run: npm install print-env
            - run: print-env CIRCLE
      - cypress/run:
          attach-workspace: true
          debug: 'cypress:cli'
          post-install:
            - run: dpkg -s print-env
            - run: print-env CIRCLE
          requires:
            - build
            - cypress/install
          start: npm start
          wait-on: 'http://localhost:3000'

